### PR TITLE
Grumpy cat

### PR DESCRIPTION
**Pull request by pwilkins05**
Added GrumpyCat feature with appropriately grumpy commentary

### CODE REVIEW

**Comment by pwilkins05** [comment]
What do you think @chrisfriedrich  ?

**Comment by chrisfriedrich** [comment]
This looks amazing.

**Comment by pwilkins05** [comment]
Doesn't seem grump enough

**Comment by chrisfriedrich** [comment]
I think it's implied that Grumpy Cat hates everything.  You might be overthinking this...

**Pull request merged**
